### PR TITLE
Fix Angular routing

### PR DESCRIPTION
**Pull request by EddyVerbruggen**
See the changes in `src/app/item/item-detail.component.ts`; you entered that page by nagivating to it and you're leaving the page by navigating to the same page as you came from, etc. So you're never popping the stack. Rather you should go back to the page you came from.

Also, please do `npm i -g nativescript` to bump to the latest NativeScript 6 version in order to run the updated repo.

### CODE REVIEW

**Comment by gauchanneelam** [comment]
Thanks @EddyVerbruggen, worked perfectly for this. But when I navigate to other different component instead of back, I'm having the same issue

**Comment by EddyVerbruggen** [comment]
Then make sure the component is destroyed when navigating away.

**Comment by gauchanneelam** [comment]
HI @EddyVerbruggen, I destroyed the component while navigating but still the issue persists. I have updated the repo. Could you please look into it?

**Comment by EddyVerbruggen** [comment]
What you're doing is navigate forward in the stack after scanning, so the component will not be destroyed. You'll have to scan and then go **back** to destroy the component, just like I showed in my PR. Alternatively you may use a modal to embed the scanner and close the modal afterwards.

**Pull request merged**
